apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-identity-deployment
  namespace: project
  labels:
    app: api-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-identity-pod
  template:
    metadata:
      labels:
        app: api-identity-pod
    spec:
      containers:
      - name: api-identity-cont
        image: bart120/yv-api-identity:1
        resources:
          limits:
            memory: "512Mi"
            cpu: "5000m"
        env:
        - name: HostRabbitmq
          value: "service-rabittmq"
        - name: RedisHost
          value: "service-user-data:6379"
        ports:
        - containerPort: 80
      restartPolicy: Always