apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabitmq-deployment
  namespace: project
  labels:
    app: rabitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabitmq-pod
  template:
    metadata:
      labels:
        app: rabitmq-pod
    spec:
      containers:
      - name: rabitmq-cont
        image: rabbitmq:3-management
        resources:
          limits:
            memory: "512Mi"
            cpu: "5000m"
        ports:
        - name: port5672
          containerPort: 5672
        - name: port15672
          containerPort: 15672
      restartPolicy: Always