apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: project
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-pod
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
      - name: database-cont
        image: bart120/yv-database:1
        resources:
          limits:
            memory: "1024Mi"
            cpu: "10000m"
        ports:
        - containerPort: 1433
      restartPolicy: Always