apiVersion: v1
kind: Service
metadata:
  name: service-database
  namespace: project
spec:
  selector:
    app: database-pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP