apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-jobs-deployment
  namespace: project
  labels:
    app: api-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-jobs-pod
  template:
    metadata:
      labels:
        app: api-jobs-pod
    spec:
      containers:
      - name: api-jobs-cont
        image: bart120/yv-api-jobs:2
        resources:
          limits:
            memory: "512Mi"
            cpu: "5000m"
        env:
        - name: ConnectionString
          value: "Server=service-database;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;"
        - name: HostRabbitmq
          value: "service-rabittmq"
        ports:
        - containerPort: 80
      restartPolicy: Always