apiVersion: v1
kind: Service
metadata:
  name: service-user-data
  namespace: project
spec:
  selector:
    app: user-data
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP