apiVersion: v1
kind: Service
metadata:
  name: service-web
  namespace: project
spec:
  selector:
    app: web-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer